### ISSUE TITLE
Errors when trying to build with Visual Studio

### ISSUE THREAD

**Issue by Nightcaat** [lufinkey/iSSB#20]
![image](https://user-images.githubusercontent.com/26909213/143787210-8aef5c03-7bc4-4f09-a14c-d02f5268fbb1.png)

**Comment by lufinkey** [comment]
What version? I'll take a look tomorrow if I can

**Comment by lufinkey** [comment]
@Nightcaat what version of visual studio are you using?

**Comment by Nightcaat** [comment]
Sorry! Been overwhelmed with a lot of stuff. I was using Visual Studio 2017 (so v142 build tools) but I didn’t have time to check if 2013 (v120) fares any better.

**Comment by lufinkey** [comment]
Hey, I've updated the visual studio project. I unfortunately wasn't able to make a 2017 because the project maker was giving me errors, but I made a 2019 project that should work. Let me know if this works for you! Apologies for taking so long

**Comment by lufinkey** [comment]
Hey, I've updated the visual studio project. I unfortunately wasn't able to make a 2017 because the project maker was giving me errors, but I made a 2019 project that should work. Let me know if this works for you! Apologies for taking so long

**Comment by lufinkey** [comment]
Hey, I've updated the visual studio project. I unfortunately wasn't able to make a 2017 because the project maker was giving me errors, but I made a 2019 project that should work. Let me know if this works for you! Apologies for taking so long

**Comment by Nightcaat** [comment]
No worries, I just installed 2019

It still complains about `boost/preprocessor/debug/error.hpp` not being present, but removing references to that along with the local inline version of lrint in `SDL2_gfxPrimitives.c` seems to be the bare minimum workaround for me to produce a working build. Thank you!

**Comment by lufinkey** [comment]
You'll likely still need those files, so I'll fix that tomorrow. That file
should be in there
