### ISSUE TITLE
White stage

### ISSUE THREAD

**Issue by GingkathFox** [lufinkey/iSSB#5]
The white stage on the stage selector should have a elipsy/seizure warning.

**Comment by lufinkey** [comment]
You're right. I'll do that

**Comment by cakeforfunx9** [comment]
I saw that you updated the SSB for iemulator, how are things going?


Sincerely, Henry Castillo


On Feb 17, 2018 at 12:06 AM, <Luis Finke<mailto:notifications@github.com>> wrote:


You're right. I'll do that

**Comment by lufinkey** [comment]
I'm so sorry I finally did this I honestly just kept forgetting
