### ISSUE TITLE
Clones, Items and others

### ISSUE THREAD

**Issue by Peddd** [lufinkey/iSSB#8]
Characters like luigi, Falco, pichu, young link/ toon link 
Could be added easier than other characters
Similar codes with only some variations
Some of these characters could be achieved by finishing achievement,
This could engage player interaction and game discussion, _and also would be very neat_

Also the inclusion of more items would be good too
Bob-bombs could be a re skin of link’s bombs, 
And crates, capsules and barrels could have the same basic code

**Comment by lufinkey** [comment]
This game is no longer being worked on
